#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

INPUT_DIR="${INPUT_DIR:-"$PROJECT_DIR/input"}"
PROCESSING_DIR="${PROCESSING_DIR:-"$PROJECT_DIR/processing"}"
OUTPUT_DIR="${OUTPUT_DIR:-"$PROJECT_DIR/output"}"
FAILED_DIR="${FAILED_DIR:-"$PROJECT_DIR/failed"}"
LOG_DIR="${LOG_DIR:-"$PROJECT_DIR/logs"}"
RUN_DIR="${RUN_DIR:-"$PROJECT_DIR/run"}"

TRIGGER_SCPT="${TRIGGER_SCPT:-"$PROJECT_DIR/scripts/trigger.scpt"}"
EXPORT_SCPT="${EXPORT_SCPT:-"$PROJECT_DIR/scripts/export.scpt"}"

QUICK_ACTION_KEY="${QUICK_ACTION_KEY:-t}"
START_CLICK_DELAY_SECONDS="${START_CLICK_DELAY_SECONDS:-5}"
WPS_CONVERSION_TIMEOUT_SECONDS="${WPS_CONVERSION_TIMEOUT_SECONDS:-1800}"
TRANSCRIBE_TIMEOUT_SECONDS="${TRANSCRIBE_TIMEOUT_SECONDS:-1800}"
TRIGGER_TIMEOUT_SECONDS="${TRIGGER_TIMEOUT_SECONDS:-20}"
EXPORT_TIMEOUT_SECONDS="${EXPORT_TIMEOUT_SECONDS:-2100}"
POLL_INTERVAL_SECONDS="${POLL_INTERVAL_SECONDS:-3}"
WATCH_HEARTBEAT_SECONDS="${WATCH_HEARTBEAT_SECONDS:-30}"
DAEMON_SLEEP_SECONDS="${DAEMON_SLEEP_SECONDS:-5}"
RESTART_WPS_EVERY_JOBS="${RESTART_WPS_EVERY_JOBS:-20}"

WPS_PROCESS_MATCH="${WPS_PROCESS_MATCH:-WPS|wps}"
WPS_KILL_NAMES=(${WPS_KILL_NAMES:-WPS wps})

# Space-separated directories where WPS may write exported txt/srt files.
EXPORT_WATCH_DIRS=(${EXPORT_WATCH_DIRS:-"$OUTPUT_DIR $HOME/Downloads $HOME/Desktop"})

SUPPORTED_EXTENSIONS="${SUPPORTED_EXTENSIONS:-m4a mp3 wav flac aac mp4 mov m4v}"
