[program:codex]
; codex 直接调用虚拟环境中的 python 解释器
command=/opt/homebrew/bin/npx codexapp --no-tunnel --no-login 
environment=PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Applications/iTerm.app/Contents/Resources/utilities"
user=jianfeisu
autostart=true
autorestart=true
stdout_logfile=/Users/jianfeisu/Work/codex/log/codex.log
stderr_logfile=/Users/jianfeisu/Work/codex/log/codex_err.log
; 停止时确保杀掉所有相关资源
stopasgroup=true
killasgroup=true


